SELECT a.AUTHOR_ID 
    , a.AUTHOR_NAME
    , b.CATEGORY
    , sum(b.PRICE * sales.SALES) as TOTAL_SALES
FROM BOOK_SALES as sales
    INNER JOIN BOOK as b ON sales.BOOK_ID = b.BOOK_ID
    INNER JOIN AUTHOR as a ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE DATE_FORMAT(sales.SALES_DATE,'%Y-%m') = '2022-01'
GROUP BY a.AUTHOR_ID , b.CATEGORY
ORDER BY a.AUTHOR_ID ASC , b.CATEGORY DESC