WITH A as (SELECT USER_ID
, PRODUCT_ID
, CONCAT(USER_ID,'-',PRODUCT_ID) as new
, COUNT(CONCAT(USER_ID,'-',PRODUCT_ID)) OVER(PARTITION BY CONCAT(USER_ID,'-',PRODUCT_ID)) as cnt
FROM ONLINE_SALE
ORDER BY PRODUCT_ID
)

SELECT USER_ID , PRODUCT_ID
FROM A
WHERE cnt>=2
GROUP BY USER_ID, PRODUCT_ID
ORDER BY USER_ID ASC, PRODUCT_ID DESC