-- SELECT DATEDIFF(ins.DATETIME, outs.DATETIME)
SELECT ins.ANIMAL_ID
     , ins.NAME
--      , (ins.DATETIME-outs.DATETIME)
FROM ANIMAL_INS ins
    INNER JOIN ANIMAL_OUTS outs ON ins.ANIMAL_ID = outs.ANIMAL_ID
ORDER BY (ins.DATETIME-outs.DATETIME) ASC
LIMIT 2
