WITH opt as (SELECT WRITER_ID
     , COUNT(WRITER_ID) as cnt
FROM USED_GOODS_BOARD
GROUP BY WRITER_ID
HAVING cnt >= 3)

SELECT
USER_ID,
NICKNAME,
CONCAT_WS(' ', CITY, STREET_ADDRESS1, STREET_ADDRESS2) 전체주소, 
CONCAT_WS('-', SUBSTR(TLNO, 1, 3), SUBSTR(TLNO, 4, 4), SUBSTR(TLNO, 8, 4)) 전화번호 
FROM USED_GOODS_USER
WHERE USER_ID IN (SELECT WRITER_ID FROM opt)
ORDER BY USER_ID DESC