WITH cte as (SELECT DATE_FORMAT(sale.SALES_DATE,'%Y') as YEAR
        , DATE_FORMAT(sale.SALES_DATE,'%m') as MONTH
        , info.GENDER
        ,info.USER_ID as id
FROM ONLINE_SALE as sale
    LEFT JOIN USER_INFO as info ON sale.USER_ID = info.USER_ID
WHERE info.GENDER IS NOT NULL
)

SELECT YEAR , MONTH , GENDER , COUNT(DISTINCT id) as USERS
FROM cte
GROUP BY YEAR , MONTH , GENDER
ORDER BY YEAR ASC , MONTH ASC, GENDER ASC