SELECT COUNT(info.ID) as FISH_COUNT
    , name.FISH_NAME
FROM FISH_NAME_INFO as name
    INNER JOIN FISH_INFO as info ON name.FISH_TYPE = info.FISH_TYPE
GROUP BY name.FISH_NAME
ORDER BY FISH_COUNT DESC