SELECT pro.PRODUCT_ID
    , pro.PRODUCT_NAME
    , SUM(ord.AMOUNT * pro.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT pro
    INNER JOIN FOOD_ORDER ord ON pro.PRODUCT_ID = ord.PRODUCT_ID
WHERE ord.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC , pro.PRODUCT_ID ASC