SELECT us.USER_ID
     , us.NICKNAME
     , SUM(board.PRICE) as TOTAL_SALES
FROM USED_GOODS_USER as us
    INNER JOIN USED_GOODS_BOARD as board ON us.USER_ID = board.WRITER_ID
WHERE STATUS = 'DONE'
GROUP BY us.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC