# SELECT MCDP_CD AS 진료과코드
#         , COUNT(DISTINCT MDDR_ID) as 5월예약건수
# FROM APPOINTMENT
# WHERE DATE_FORMAT(APNT_YMD,'%Y-%m-%d') BETWEEN '2022-05-01' AND '2022-05-31'
# -- AND APNT_CNCL_YN = 'N'
# GROUP BY MCDP_CD
# ORDER BY 5월예약건수 ASC , 진료과코드 ASC

SELECT MCDP_CD AS 진료과코드
        , COUNT(MDDR_ID) as 5월예약건수
FROM APPOINTMENT
WHERE MONTH(APNT_YMD) = 05
GROUP BY MCDP_CD
ORDER BY 5월예약건수 ASC , 진료과코드 ASC