SELECT SUM(CASE WHEN name.FISH_NAME = 'BASS' THEN 1 
            WHEN name.FISH_NAME = 'SNAPPER' THEN 1 END ) as FISH_COUNT
FROM FISH_INFO info
    INNER JOIN FISH_NAME_INFO as name ON info.FISH_TYPE = name.FISH_TYPE
