WITH sc as (SELECT SUM(SCORE) as SCORE
    , gr.EMP_NO
    , emp.EMP_NAME
    , emp.POSITION
    , emp.EMAIL
FROM HR_DEPARTMENT as dep
    INNER JOIN HR_EMPLOYEES as emp ON dep.DEPT_ID = emp.DEPT_ID
    INNER JOIN HR_GRADE as gr ON gr.EMP_NO = emp.EMP_NO
WHERE gr.YEAR = 2022
GROUP BY EMP_NO 
ORDER BY SCORE DESC)

SELECT *
FROM sc
WHERE SCORE = (SELECT MAX(SCORE) FROM sc)