-- 코드를 입력하세요
SELECT info.INGREDIENT_TYPE
     , SUM(sales.TOTAL_ORDER)as TOTAL_ORDER
FROM FIRST_HALF as sales
    INNER JOIN ICECREAM_INFO as info ON sales.FLAVOR = info.FLAVOR
GROUP BY info.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC