WITH price as (SELECT CATEGORY 
    , ROW_NUMBER() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) rn
    , PRICE 
    , PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자','국','김치','식용유')
)

SELECT CATEGORY
        , PRICE as MAX_PRICE
        , PRODUCT_NAME
FROM price
WHERE rn = 1
ORDER BY MAX_PRICE DESC