WITH cte as (SELECT  FISH_TYPE
        , CASE WHEN LENGTH IS NULL THEN 10 ELSE LENGTH END as LENGTH
FROM FISH_INFO
)

SELECT COUNT(FISH_TYPE) as FISH_COUNT
        , MAX(LENGTH) AS MAX_LENGTH
        , FISH_TYPE
FROM cte
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE ASC