SELECT BOOK_ID
    , a.AUTHOR_NAME
    , DATE_FORMAT(b.PUBLISHED_DATE, '%Y-%m-%d')
FROM BOOK b
  INNER JOIN AUTHOR as a ON a.AUTHOR_ID = b.AUTHOR_ID
WHERE CATEGORY = '경제'
ORDER BY b.PUBLISHED_DATE ASC